import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Box } from '@mui/material'
import NavBar from './components/NavBar'
import VisitView from './components/VisitView'
import Layout from './components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box width="100%" height="100vh " sx={{ position: "relative" }}>
          <NavBar />
          <VisitView />
        </Box>
      </Layout>
    </>
  )
}
